### ISSUE TITLE
PDB API importer fails (again :( )

### ISSUE THREAD

**Issue by wfenrich** [CeON/mxrdr-extension#114]

**Comment by wfenrich** [comment]
[2022-03-10T12:48:16.403+0000] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.importers.ui.ImporterForm] [tid: _ThreadID=31 _ThreadName=http-listener-1(3)] [timeMillis: 1646916496403] [levelValue: 900] [[
  Exception during importer invocation
java.lang.NullPointerException
    at java.util.Objects.requireNonNull(Objects.java:203)
    at java.util.Optional.<init>(Optional.java:96)
    at java.util.Optional.of(Optional.java:108)
    at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:193)
    at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:190)
    at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
    at pl.edu.icm.pl.mxrdr.extension.importer.pdb.PdbDataContainer.chooseReflectionsShell(PdbDataContainer.java:196)
    at pl.edu.icm.pl.mxrdr.extension.importer.pdb.PdbDataContainer.init(PdbDataContainer.java:39)
    at pl.edu.icm.pl.mxrdr.extension.importer.pdb.PdbApiImporter.fetchMetadata(PdbApiImporter.java:73)
    at edu.harvard.iq.dataverse.importers.ui.ImporterForm.nextStep(ImporterForm.java:156)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
